### ISSUE TITLE
Update for NSX-T 2.3

### ISSUE THREAD

**Issue by simonkrenger** [vmware/go-vmware-nsxt#17]
Greetings,

We are using your library to automate many common tasks for our NSX-T environment. Our environment is using NSX-T 2.3.0.2. Most of the generated code for 2.0 still works with 2.3, however there are now a few things missing. A good example is the `role` field in the `PrincipalIdentity` struct.

I regenerated the code using `swagger-codegen`, however without the template used I get a completely different code structure.

* Could you provide the `swagger-codegen` arguments you used to generate the code?
* Any chance that the library is regenerated for version 2.3?

Thank you very much.

Regards, Simon

**Comment by annakhm** [comment]
Hello @simonkrenger, thanks for filing this. 
As of now we are not planning to regenerate the sdk for 2.3, since our next priority would be to generate new sdk for policy API, which is an intent-based abstraction layer above NSX-T.
We did a bunch of half-manual post-processing after generating the initial 2.0 API with swagger, f.e. folderization, therefore I can not recommend you an easy way to regenerate missing resources. However, for small fixes, you are welcome to manually add missing fields in existing resources (f.e. as was done here https://github.com/vmware/go-vmware-nsxt/pull/12)

Hope it helps and sorry for the inconvenience,
Anna

**Comment by simonkrenger** [comment]
Hello @annakhm 

Thank you for your update and the additional information.
We'll discuss on how to proceed and will create pull requests for changes if necessary.

Regards,
Simon
